<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container6uhUSyK\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container6uhUSyK/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container6uhUSyK.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container6uhUSyK\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \Container6uhUSyK\App_KernelDevDebugContainer([
    'container.build_hash' => '6uhUSyK',
    'container.build_id' => '23f54098',
    'container.build_time' => 1684498973,
], __DIR__.\DIRECTORY_SEPARATOR.'Container6uhUSyK');
