<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerZebqBwr\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerZebqBwr/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerZebqBwr.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerZebqBwr\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerZebqBwr\App_KernelDevDebugContainer([
    'container.build_hash' => 'ZebqBwr',
    'container.build_id' => '55e6c22b',
    'container.build_time' => 1684685686,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerZebqBwr');
